syntax = "proto3";

package game;
option go_package = "./pb";



message Req_Node_CreatePlayer{
  int64 userID =  1;
  int32 serverID = 2;
  string nickname = 4;
}

message Rsp_Node_CreatePlayer{
  int64 playerID = 1;
  int32 serverID = 2;
  int64 ID = 3;
  int64 userID = 4;
  string nickname = 5;
  string token = 6;
  int32 state = 7;
}

message Req_Node_ConnCount{
}

message Rsp_Node_ConnCount{
  int32 Count = 1;
}

message Req_Node_OrderPaid{
  int64 playerID = 1;
  int32 serverID = 2;
  string orderId = 3;
}

message Rsp_Node_OrderPaid{
  string orderId = 1;
  int32  state = 2;
}

message Req_Node_NewBaseMail{
  int64 mailId = 1;
}

message Rsp_Node_NewBaseMail{
}


message MatchWaiter{
  string teamId = 1;
  double score = 2;
  string teamLeader = 3;
  repeated string teamMember = 4;
}

message Req_Node_NewMatch{
  MatchWaiter waiter = 1;
}

message Rsp_Node_NewMatch{
  int32 state = 1;
  int64 expectedWaitTime = 2;
  string errReason = 3;
}

// 取消匹配
message Req_Node_CancelMatch{
  int64 playerId = 1;
  int32 serverId = 2;
}

message Rsp_Node_CancelMatch{
  int32 state = 1;
}

// 匹配成功
message Req_Node_MatchSuccess{
  int32 state = 1;
  repeated string matchMember = 2;
  string roomId = 3;
  string roomAddr = 4;
}

message Rsp_Node_MatchSuccess{
  int32 state = 1;
}

// 创建房间
message Req_Node_CreateRoom{
  int32 roomType = 1;
  int32 confId = 2;
  repeated string matchMember = 3;
  string matchId = 4;
}

message Rsp_Node_CreateRoom{
  int32 state = 1;
  string roomId = 2;
  string roomAddr = 3;
}


message Req_Node_MakeConnToRoom{
  int64 playerId = 1;
  string roomId = 2;
  string roomAddr = 3;
}

message Rsp_Node_MakeConnToRoom{
  int32 state = 1;
}