// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: src/msg_rank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RankItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentKey string  `protobuf:"bytes,1,opt,name=contentKey,proto3" json:"contentKey,omitempty"`
	Score      float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Rank       int64   `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	HeadShot   string  `protobuf:"bytes,4,opt,name=head_shot,json=headShot,proto3" json:"head_shot,omitempty"`
}

func (x *RankItemInfo) Reset() {
	*x = RankItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_rank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItemInfo) ProtoMessage() {}

func (x *RankItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_rank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItemInfo.ProtoReflect.Descriptor instead.
func (*RankItemInfo) Descriptor() ([]byte, []int) {
	return file_src_msg_rank_proto_rawDescGZIP(), []int{0}
}

func (x *RankItemInfo) GetContentKey() string {
	if x != nil {
		return x.ContentKey
	}
	return ""
}

func (x *RankItemInfo) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankItemInfo) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankItemInfo) GetHeadShot() string {
	if x != nil {
		return x.HeadShot
	}
	return ""
}

type Req_RankList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankType int32 `protobuf:"varint,1,opt,name=rankType,proto3" json:"rankType,omitempty"` // 排行榜类型
}

func (x *Req_RankList) Reset() {
	*x = Req_RankList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_rank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_RankList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_RankList) ProtoMessage() {}

func (x *Req_RankList) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_rank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_RankList.ProtoReflect.Descriptor instead.
func (*Req_RankList) Descriptor() ([]byte, []int) {
	return file_src_msg_rank_proto_rawDescGZIP(), []int{1}
}

func (x *Req_RankList) GetRankType() int32 {
	if x != nil {
		return x.RankType
	}
	return 0
}

type Rsp_RankList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankList []*RankItemInfo `protobuf:"bytes,1,rep,name=rank_list,json=rankList,proto3" json:"rank_list,omitempty"` // 排行榜类型
	MyScore  float64         `protobuf:"fixed64,2,opt,name=my_score,json=myScore,proto3" json:"my_score,omitempty"`
	MyRank   int64           `protobuf:"varint,3,opt,name=my_rank,json=myRank,proto3" json:"my_rank,omitempty"`
}

func (x *Rsp_RankList) Reset() {
	*x = Rsp_RankList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_rank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_RankList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_RankList) ProtoMessage() {}

func (x *Rsp_RankList) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_rank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_RankList.ProtoReflect.Descriptor instead.
func (*Rsp_RankList) Descriptor() ([]byte, []int) {
	return file_src_msg_rank_proto_rawDescGZIP(), []int{2}
}

func (x *Rsp_RankList) GetRankList() []*RankItemInfo {
	if x != nil {
		return x.RankList
	}
	return nil
}

func (x *Rsp_RankList) GetMyScore() float64 {
	if x != nil {
		return x.MyScore
	}
	return 0
}

func (x *Rsp_RankList) GetMyRank() int64 {
	if x != nil {
		return x.MyRank
	}
	return 0
}

var File_src_msg_rank_proto protoreflect.FileDescriptor

var file_src_msg_rank_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x75, 0x0a, 0x0c, 0x52, 0x61,
	0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x72, 0x61, 0x6e, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x73, 0x68, 0x6f,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65, 0x61, 0x64, 0x53, 0x68, 0x6f,
	0x74, 0x22, 0x2a, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x5f, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x22, 0x73, 0x0a,
	0x0c, 0x52, 0x73, 0x70, 0x5f, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a,
	0x09, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x07, 0x6d, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x79, 0x5f,
	0x72, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x79, 0x52, 0x61,
	0x6e, 0x6b, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_src_msg_rank_proto_rawDescOnce sync.Once
	file_src_msg_rank_proto_rawDescData = file_src_msg_rank_proto_rawDesc
)

func file_src_msg_rank_proto_rawDescGZIP() []byte {
	file_src_msg_rank_proto_rawDescOnce.Do(func() {
		file_src_msg_rank_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_msg_rank_proto_rawDescData)
	})
	return file_src_msg_rank_proto_rawDescData
}

var file_src_msg_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_msg_rank_proto_goTypes = []interface{}{
	(*RankItemInfo)(nil), // 0: game.RankItemInfo
	(*Req_RankList)(nil), // 1: game.Req_RankList
	(*Rsp_RankList)(nil), // 2: game.Rsp_RankList
}
var file_src_msg_rank_proto_depIdxs = []int32{
	0, // 0: game.Rsp_RankList.rank_list:type_name -> game.RankItemInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_msg_rank_proto_init() }
func file_src_msg_rank_proto_init() {
	if File_src_msg_rank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_msg_rank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_rank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_RankList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_rank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_RankList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_msg_rank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_msg_rank_proto_goTypes,
		DependencyIndexes: file_src_msg_rank_proto_depIdxs,
		MessageInfos:      file_src_msg_rank_proto_msgTypes,
	}.Build()
	File_src_msg_rank_proto = out.File
	file_src_msg_rank_proto_rawDesc = nil
	file_src_msg_rank_proto_goTypes = nil
	file_src_msg_rank_proto_depIdxs = nil
}
