// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: src/msg_code.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==========================
// 🔥 所有协议号 全部在这里定义
// ==========================
type MsgID int32

const (
	MsgID_MSG_INVALID MsgID = 0 // 必须从0开始
	MsgID_MSG_GM_Cmd  MsgID = 1 // 测试用gm
	// 网关 ↔ 游戏服
	MsgID_MSG_AUTH      MsgID = 10001 // 鉴权
	MsgID_MSG_HeartBeat MsgID = 10002 // 心跳
	MsgID_MSG_Kick      MsgID = 10003 // 下线
	// 游戏业务 start from 20000
	MsgID_MSG_Req_EnterGame MsgID = 20001 // 进入游戏请求
	MsgID_MSG_Rsp_EnterGame MsgID = 20002 // 进入游戏返回
	MsgID_MSG_Req_BagData MsgID = 21001
	MsgID_MSG_Rsp_BagData MsgID = 21002
	MsgID_MSG_Req_CreateOrder MsgID = 21101
	MsgID_MSG_Rsp_CreateOrder MsgID = 21102 // 进入游戏
)

// Enum value maps for MsgID.
var (
	MsgID_name = map[int32]string{
		0:     "MSG_INVALID",
		1:     "MSG_GM_Cmd",
		10001: "MSG_AUTH",
		10002: "MSG_HeartBeat",
		10003: "MSG_Kick",
		20001: "MSG_Req_EnterGame",
		20002: "MSG_Rsp_EnterGame",
		21001: "MSG_Req_BagData",
		21002: "MSG_Rsp_BagData",
		21101: "MSG_Req_CreateOrder",
		21102: "MSG_Rsp_CreateOrder",
	}
	MsgID_value = map[string]int32{
		"MSG_INVALID":         0,
		"MSG_GM_Cmd":          1,
		"MSG_AUTH":            10001,
		"MSG_HeartBeat":       10002,
		"MSG_Kick":            10003,
		"MSG_Req_EnterGame":   20001,
		"MSG_Rsp_EnterGame":   20002,
		"MSG_Req_BagData":     21001,
		"MSG_Rsp_BagData":     21002,
		"MSG_Req_CreateOrder": 21101,
		"MSG_Rsp_CreateOrder": 21102,
	}
)

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_src_msg_code_proto_enumTypes[0].Descriptor()
}

func (MsgID) Type() protoreflect.EnumType {
	return &file_src_msg_code_proto_enumTypes[0]
}

func (x MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgID.Descriptor instead.
func (MsgID) EnumDescriptor() ([]byte, []int) {
	return file_src_msg_code_proto_rawDescGZIP(), []int{0}
}

var File_src_msg_code_proto protoreflect.FileDescriptor

var file_src_msg_code_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x2a, 0xf0, 0x01, 0x0a, 0x05, 0x4d,
	0x73, 0x67, 0x49, 0x44, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x53, 0x47, 0x5f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x53, 0x47, 0x5f, 0x47, 0x4d, 0x5f,
	0x43, 0x6d, 0x64, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x08, 0x4d, 0x53, 0x47, 0x5f, 0x41, 0x55, 0x54,
	0x48, 0x10, 0x91, 0x4e, 0x12, 0x12, 0x0a, 0x0d, 0x4d, 0x53, 0x47, 0x5f, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x10, 0x92, 0x4e, 0x12, 0x0d, 0x0a, 0x08, 0x4d, 0x53, 0x47, 0x5f,
	0x4b, 0x69, 0x63, 0x6b, 0x10, 0x93, 0x4e, 0x12, 0x17, 0x0a, 0x11, 0x4d, 0x53, 0x47, 0x5f, 0x52,
	0x65, 0x71, 0x5f, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x10, 0xa1, 0x9c, 0x01,
	0x12, 0x17, 0x0a, 0x11, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x73, 0x70, 0x5f, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x47, 0x61, 0x6d, 0x65, 0x10, 0xa2, 0x9c, 0x01, 0x12, 0x15, 0x0a, 0x0f, 0x4d, 0x53, 0x47,
	0x5f, 0x52, 0x65, 0x71, 0x5f, 0x42, 0x61, 0x67, 0x44, 0x61, 0x74, 0x61, 0x10, 0x89, 0xa4, 0x01,
	0x12, 0x15, 0x0a, 0x0f, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x73, 0x70, 0x5f, 0x42, 0x61, 0x67, 0x44,
	0x61, 0x74, 0x61, 0x10, 0x8a, 0xa4, 0x01, 0x12, 0x19, 0x0a, 0x13, 0x4d, 0x53, 0x47, 0x5f, 0x52,
	0x65, 0x71, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x10, 0xed,
	0xa4, 0x01, 0x12, 0x19, 0x0a, 0x13, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x73, 0x70, 0x5f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x10, 0xee, 0xa4, 0x01, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_msg_code_proto_rawDescOnce sync.Once
	file_src_msg_code_proto_rawDescData = file_src_msg_code_proto_rawDesc
)

func file_src_msg_code_proto_rawDescGZIP() []byte {
	file_src_msg_code_proto_rawDescOnce.Do(func() {
		file_src_msg_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_msg_code_proto_rawDescData)
	})
	return file_src_msg_code_proto_rawDescData
}

var file_src_msg_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_msg_code_proto_goTypes = []interface{}{
	(MsgID)(0), // 0: game.MsgID
}
var file_src_msg_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_msg_code_proto_init() }
func file_src_msg_code_proto_init() {
	if File_src_msg_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_msg_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_msg_code_proto_goTypes,
		DependencyIndexes: file_src_msg_code_proto_depIdxs,
		EnumInfos:         file_src_msg_code_proto_enumTypes,
	}.Build()
	File_src_msg_code_proto = out.File
	file_src_msg_code_proto_rawDesc = nil
	file_src_msg_code_proto_goTypes = nil
	file_src_msg_code_proto_depIdxs = nil
}
