// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: src/msg_player.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req_LoginGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Req_LoginGame) Reset() {
	*x = Req_LoginGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_LoginGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_LoginGame) ProtoMessage() {}

func (x *Req_LoginGame) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_LoginGame.ProtoReflect.Descriptor instead.
func (*Req_LoginGame) Descriptor() ([]byte, []int) {
	return file_src_msg_player_proto_rawDescGZIP(), []int{0}
}

type Rsp_LoginGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
}

func (x *Rsp_LoginGame) Reset() {
	*x = Rsp_LoginGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_LoginGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_LoginGame) ProtoMessage() {}

func (x *Rsp_LoginGame) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_LoginGame.ProtoReflect.Descriptor instead.
func (*Rsp_LoginGame) Descriptor() ([]byte, []int) {
	return file_src_msg_player_proto_rawDescGZIP(), []int{1}
}

func (x *Rsp_LoginGame) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type Req_StartMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Req_StartMatch) Reset() {
	*x = Req_StartMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_player_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_StartMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_StartMatch) ProtoMessage() {}

func (x *Req_StartMatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_player_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_StartMatch.ProtoReflect.Descriptor instead.
func (*Req_StartMatch) Descriptor() ([]byte, []int) {
	return file_src_msg_player_proto_rawDescGZIP(), []int{2}
}

type Rsp_StartMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
}

func (x *Rsp_StartMatch) Reset() {
	*x = Rsp_StartMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_player_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_StartMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_StartMatch) ProtoMessage() {}

func (x *Rsp_StartMatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_player_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_StartMatch.ProtoReflect.Descriptor instead.
func (*Rsp_StartMatch) Descriptor() ([]byte, []int) {
	return file_src_msg_player_proto_rawDescGZIP(), []int{3}
}

func (x *Rsp_StartMatch) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type Notify_MatchSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Notify_MatchSuccess) Reset() {
	*x = Notify_MatchSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_player_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notify_MatchSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify_MatchSuccess) ProtoMessage() {}

func (x *Notify_MatchSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_player_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify_MatchSuccess.ProtoReflect.Descriptor instead.
func (*Notify_MatchSuccess) Descriptor() ([]byte, []int) {
	return file_src_msg_player_proto_rawDescGZIP(), []int{4}
}

func (x *Notify_MatchSuccess) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *Notify_MatchSuccess) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Req_EnterRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Req_EnterRoom) Reset() {
	*x = Req_EnterRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_player_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_EnterRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_EnterRoom) ProtoMessage() {}

func (x *Req_EnterRoom) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_player_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_EnterRoom.ProtoReflect.Descriptor instead.
func (*Req_EnterRoom) Descriptor() ([]byte, []int) {
	return file_src_msg_player_proto_rawDescGZIP(), []int{5}
}

type Rsp_EnterRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
}

func (x *Rsp_EnterRoom) Reset() {
	*x = Rsp_EnterRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_player_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_EnterRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_EnterRoom) ProtoMessage() {}

func (x *Rsp_EnterRoom) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_player_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_EnterRoom.ProtoReflect.Descriptor instead.
func (*Rsp_EnterRoom) Descriptor() ([]byte, []int) {
	return file_src_msg_player_proto_rawDescGZIP(), []int{6}
}

func (x *Rsp_EnterRoom) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type Req_QuitRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Req_QuitRoom) Reset() {
	*x = Req_QuitRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_player_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_QuitRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_QuitRoom) ProtoMessage() {}

func (x *Req_QuitRoom) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_player_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_QuitRoom.ProtoReflect.Descriptor instead.
func (*Req_QuitRoom) Descriptor() ([]byte, []int) {
	return file_src_msg_player_proto_rawDescGZIP(), []int{7}
}

type Rsp_QuitRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
}

func (x *Rsp_QuitRoom) Reset() {
	*x = Rsp_QuitRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_player_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_QuitRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_QuitRoom) ProtoMessage() {}

func (x *Rsp_QuitRoom) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_player_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_QuitRoom.ProtoReflect.Descriptor instead.
func (*Rsp_QuitRoom) Descriptor() ([]byte, []int) {
	return file_src_msg_player_proto_rawDescGZIP(), []int{8}
}

func (x *Rsp_QuitRoom) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_src_msg_player_proto protoreflect.FileDescriptor

var file_src_msg_player_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x0f, 0x0a, 0x0d,
	0x52, 0x65, 0x71, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a,
	0x0d, 0x52, 0x73, 0x70, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x5f, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x28, 0x0a, 0x0e, 0x52, 0x73, 0x70, 0x5f,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x45, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x71,
	0x5f, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x22, 0x27, 0x0a, 0x0d, 0x52, 0x73,
	0x70, 0x5f, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x5f, 0x51, 0x75, 0x69, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x22, 0x26, 0x0a, 0x0c, 0x52, 0x73, 0x70, 0x5f, 0x51, 0x75, 0x69, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_msg_player_proto_rawDescOnce sync.Once
	file_src_msg_player_proto_rawDescData = file_src_msg_player_proto_rawDesc
)

func file_src_msg_player_proto_rawDescGZIP() []byte {
	file_src_msg_player_proto_rawDescOnce.Do(func() {
		file_src_msg_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_msg_player_proto_rawDescData)
	})
	return file_src_msg_player_proto_rawDescData
}

var file_src_msg_player_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_src_msg_player_proto_goTypes = []interface{}{
	(*Req_LoginGame)(nil),       // 0: game.Req_LoginGame
	(*Rsp_LoginGame)(nil),       // 1: game.Rsp_LoginGame
	(*Req_StartMatch)(nil),      // 2: game.Req_StartMatch
	(*Rsp_StartMatch)(nil),      // 3: game.Rsp_StartMatch
	(*Notify_MatchSuccess)(nil), // 4: game.Notify_MatchSuccess
	(*Req_EnterRoom)(nil),       // 5: game.Req_EnterRoom
	(*Rsp_EnterRoom)(nil),       // 6: game.Rsp_EnterRoom
	(*Req_QuitRoom)(nil),        // 7: game.Req_QuitRoom
	(*Rsp_QuitRoom)(nil),        // 8: game.Rsp_QuitRoom
}
var file_src_msg_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_msg_player_proto_init() }
func file_src_msg_player_proto_init() {
	if File_src_msg_player_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_msg_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_LoginGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_LoginGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_player_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_StartMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_player_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_StartMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_player_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notify_MatchSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_player_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_EnterRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_player_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_EnterRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_player_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_QuitRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_player_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_QuitRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_msg_player_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_msg_player_proto_goTypes,
		DependencyIndexes: file_src_msg_player_proto_depIdxs,
		MessageInfos:      file_src_msg_player_proto_msgTypes,
	}.Build()
	File_src_msg_player_proto = out.File
	file_src_msg_player_proto_rawDesc = nil
	file_src_msg_player_proto_goTypes = nil
	file_src_msg_player_proto_depIdxs = nil
}
