// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: msg_auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 到游戏服的验证
type Req_AuthClientToGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID    int64  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"` // 角色id
	ServerID    int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	GatewayAddr string `protobuf:"bytes,3,opt,name=gatewayAddr,proto3" json:"gatewayAddr,omitempty"` //
}

func (x *Req_AuthClientToGame) Reset() {
	*x = Req_AuthClientToGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_AuthClientToGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_AuthClientToGame) ProtoMessage() {}

func (x *Req_AuthClientToGame) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_AuthClientToGame.ProtoReflect.Descriptor instead.
func (*Req_AuthClientToGame) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Req_AuthClientToGame) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *Req_AuthClientToGame) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Req_AuthClientToGame) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

type Rsp_AuthClientToGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
}

func (x *Rsp_AuthClientToGame) Reset() {
	*x = Rsp_AuthClientToGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_AuthClientToGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_AuthClientToGame) ProtoMessage() {}

func (x *Rsp_AuthClientToGame) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_AuthClientToGame.ProtoReflect.Descriptor instead.
func (*Rsp_AuthClientToGame) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Rsp_AuthClientToGame) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

// 到房间服的验证
type Req_AuthClientToRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID int64  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"` // 角色id
	ServerID int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	RoomId   string `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"` //
}

func (x *Req_AuthClientToRoom) Reset() {
	*x = Req_AuthClientToRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_AuthClientToRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_AuthClientToRoom) ProtoMessage() {}

func (x *Req_AuthClientToRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_AuthClientToRoom.ProtoReflect.Descriptor instead.
func (*Req_AuthClientToRoom) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{2}
}

func (x *Req_AuthClientToRoom) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *Req_AuthClientToRoom) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Req_AuthClientToRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type Rsp_AuthClientToRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
}

func (x *Rsp_AuthClientToRoom) Reset() {
	*x = Rsp_AuthClientToRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_AuthClientToRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_AuthClientToRoom) ProtoMessage() {}

func (x *Rsp_AuthClientToRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_AuthClientToRoom.ProtoReflect.Descriptor instead.
func (*Rsp_AuthClientToRoom) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{3}
}

func (x *Rsp_AuthClientToRoom) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type Req_AuthClientToGateWay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UerID    int64  `protobuf:"varint,1,opt,name=uerID,proto3" json:"uerID,omitempty"`
	PlayerID int64  `protobuf:"varint,2,opt,name=playerID,proto3" json:"playerID,omitempty"`
	ServerID int32  `protobuf:"varint,3,opt,name=serverID,proto3" json:"serverID,omitempty"`
	Token    string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Req_AuthClientToGateWay) Reset() {
	*x = Req_AuthClientToGateWay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_AuthClientToGateWay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_AuthClientToGateWay) ProtoMessage() {}

func (x *Req_AuthClientToGateWay) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_AuthClientToGateWay.ProtoReflect.Descriptor instead.
func (*Req_AuthClientToGateWay) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{4}
}

func (x *Req_AuthClientToGateWay) GetUerID() int64 {
	if x != nil {
		return x.UerID
	}
	return 0
}

func (x *Req_AuthClientToGateWay) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *Req_AuthClientToGateWay) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Req_AuthClientToGateWay) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Rsp_AuthClientToGateWay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode    int32           `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Reason     string          `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	PlayerInfo *GamePlayerInfo `protobuf:"bytes,3,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
}

func (x *Rsp_AuthClientToGateWay) Reset() {
	*x = Rsp_AuthClientToGateWay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_AuthClientToGateWay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_AuthClientToGateWay) ProtoMessage() {}

func (x *Rsp_AuthClientToGateWay) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_AuthClientToGateWay.ProtoReflect.Descriptor instead.
func (*Rsp_AuthClientToGateWay) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{5}
}

func (x *Rsp_AuthClientToGateWay) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *Rsp_AuthClientToGateWay) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Rsp_AuthClientToGateWay) GetPlayerInfo() *GamePlayerInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

type Req_HeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Req_HeartBeat) Reset() {
	*x = Req_HeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_HeartBeat) ProtoMessage() {}

func (x *Req_HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_HeartBeat.ProtoReflect.Descriptor instead.
func (*Req_HeartBeat) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{6}
}

type Notify_Kick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=Reason,proto3" json:"Reason,omitempty"`
}

func (x *Notify_Kick) Reset() {
	*x = Notify_Kick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notify_Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify_Kick) ProtoMessage() {}

func (x *Notify_Kick) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify_Kick.ProtoReflect.Descriptor instead.
func (*Notify_Kick) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{7}
}

func (x *Notify_Kick) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_msg_auth_proto protoreflect.FileDescriptor

var file_msg_auth_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x1a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x5f,
	0x41, 0x75, 0x74, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x47, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x22, 0x2e, 0x0a, 0x14, 0x52, 0x73,
	0x70, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x47, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x66, 0x0a, 0x14, 0x52, 0x65,
	0x71, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x52, 0x73, 0x70, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x7d, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x47, 0x61, 0x74, 0x65, 0x57, 0x61, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x75, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x75, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x81, 0x01, 0x0a, 0x17, 0x52, 0x73, 0x70, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x47, 0x61, 0x74, 0x65, 0x57, 0x61, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x34, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x5f, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x22, 0x25, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x5f, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_auth_proto_rawDescOnce sync.Once
	file_msg_auth_proto_rawDescData = file_msg_auth_proto_rawDesc
)

func file_msg_auth_proto_rawDescGZIP() []byte {
	file_msg_auth_proto_rawDescOnce.Do(func() {
		file_msg_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_auth_proto_rawDescData)
	})
	return file_msg_auth_proto_rawDescData
}

var file_msg_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_msg_auth_proto_goTypes = []interface{}{
	(*Req_AuthClientToGame)(nil),    // 0: game.Req_AuthClientToGame
	(*Rsp_AuthClientToGame)(nil),    // 1: game.Rsp_AuthClientToGame
	(*Req_AuthClientToRoom)(nil),    // 2: game.Req_AuthClientToRoom
	(*Rsp_AuthClientToRoom)(nil),    // 3: game.Rsp_AuthClientToRoom
	(*Req_AuthClientToGateWay)(nil), // 4: game.Req_AuthClientToGateWay
	(*Rsp_AuthClientToGateWay)(nil), // 5: game.Rsp_AuthClientToGateWay
	(*Req_HeartBeat)(nil),           // 6: game.Req_HeartBeat
	(*Notify_Kick)(nil),             // 7: game.Notify_Kick
	(*GamePlayerInfo)(nil),          // 8: game.GamePlayerInfo
}
var file_msg_auth_proto_depIdxs = []int32{
	8, // 0: game.Rsp_AuthClientToGateWay.playerInfo:type_name -> game.GamePlayerInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msg_auth_proto_init() }
func file_msg_auth_proto_init() {
	if File_msg_auth_proto != nil {
		return
	}
	file_msg_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_AuthClientToGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_AuthClientToGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_AuthClientToRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_AuthClientToRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_AuthClientToGateWay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_AuthClientToGateWay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_HeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notify_Kick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_auth_proto_goTypes,
		DependencyIndexes: file_msg_auth_proto_depIdxs,
		MessageInfos:      file_msg_auth_proto_msgTypes,
	}.Build()
	File_msg_auth_proto = out.File
	file_msg_auth_proto_rawDesc = nil
	file_msg_auth_proto_goTypes = nil
	file_msg_auth_proto_depIdxs = nil
}
