// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: msg_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req_Node_CreatePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ServerID int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *Req_Node_CreatePlayer) Reset() {
	*x = Req_Node_CreatePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_CreatePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_CreatePlayer) ProtoMessage() {}

func (x *Req_Node_CreatePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_CreatePlayer.ProtoReflect.Descriptor instead.
func (*Req_Node_CreatePlayer) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{0}
}

func (x *Req_Node_CreatePlayer) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Req_Node_CreatePlayer) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Req_Node_CreatePlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type Rsp_Node_CreatePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID int64  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	ServerID int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	ID       int64  `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID   int64  `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	Nickname string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Token    string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	State    int32  `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Rsp_Node_CreatePlayer) Reset() {
	*x = Rsp_Node_CreatePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_CreatePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_CreatePlayer) ProtoMessage() {}

func (x *Rsp_Node_CreatePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_CreatePlayer.ProtoReflect.Descriptor instead.
func (*Rsp_Node_CreatePlayer) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{1}
}

func (x *Rsp_Node_CreatePlayer) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *Rsp_Node_CreatePlayer) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Rsp_Node_CreatePlayer) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Rsp_Node_CreatePlayer) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Rsp_Node_CreatePlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Rsp_Node_CreatePlayer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Rsp_Node_CreatePlayer) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type Req_Node_ConnCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Req_Node_ConnCount) Reset() {
	*x = Req_Node_ConnCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_ConnCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_ConnCount) ProtoMessage() {}

func (x *Req_Node_ConnCount) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_ConnCount.ProtoReflect.Descriptor instead.
func (*Req_Node_ConnCount) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{2}
}

type Rsp_Node_ConnCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *Rsp_Node_ConnCount) Reset() {
	*x = Rsp_Node_ConnCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_ConnCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_ConnCount) ProtoMessage() {}

func (x *Rsp_Node_ConnCount) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_ConnCount.ProtoReflect.Descriptor instead.
func (*Rsp_Node_ConnCount) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{3}
}

func (x *Rsp_Node_ConnCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Req_Node_OrderPaid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID int64  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	ServerID int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	OrderId  string `protobuf:"bytes,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *Req_Node_OrderPaid) Reset() {
	*x = Req_Node_OrderPaid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_OrderPaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_OrderPaid) ProtoMessage() {}

func (x *Req_Node_OrderPaid) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_OrderPaid.ProtoReflect.Descriptor instead.
func (*Req_Node_OrderPaid) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{4}
}

func (x *Req_Node_OrderPaid) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *Req_Node_OrderPaid) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Req_Node_OrderPaid) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type Rsp_Node_OrderPaid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	State   int32  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Rsp_Node_OrderPaid) Reset() {
	*x = Rsp_Node_OrderPaid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_OrderPaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_OrderPaid) ProtoMessage() {}

func (x *Rsp_Node_OrderPaid) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_OrderPaid.ProtoReflect.Descriptor instead.
func (*Rsp_Node_OrderPaid) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{5}
}

func (x *Rsp_Node_OrderPaid) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Rsp_Node_OrderPaid) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type Req_Node_NewBaseMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId int64 `protobuf:"varint,1,opt,name=mailId,proto3" json:"mailId,omitempty"`
}

func (x *Req_Node_NewBaseMail) Reset() {
	*x = Req_Node_NewBaseMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_NewBaseMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_NewBaseMail) ProtoMessage() {}

func (x *Req_Node_NewBaseMail) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_NewBaseMail.ProtoReflect.Descriptor instead.
func (*Req_Node_NewBaseMail) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{6}
}

func (x *Req_Node_NewBaseMail) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type Rsp_Node_NewBaseMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Rsp_Node_NewBaseMail) Reset() {
	*x = Rsp_Node_NewBaseMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_NewBaseMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_NewBaseMail) ProtoMessage() {}

func (x *Rsp_Node_NewBaseMail) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_NewBaseMail.ProtoReflect.Descriptor instead.
func (*Rsp_Node_NewBaseMail) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{7}
}

type MatchWaiter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId     string   `protobuf:"bytes,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	Score      float64  `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	TeamLeader string   `protobuf:"bytes,3,opt,name=teamLeader,proto3" json:"teamLeader,omitempty"`
	TeamMember []string `protobuf:"bytes,4,rep,name=teamMember,proto3" json:"teamMember,omitempty"`
}

func (x *MatchWaiter) Reset() {
	*x = MatchWaiter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchWaiter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchWaiter) ProtoMessage() {}

func (x *MatchWaiter) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchWaiter.ProtoReflect.Descriptor instead.
func (*MatchWaiter) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{8}
}

func (x *MatchWaiter) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *MatchWaiter) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MatchWaiter) GetTeamLeader() string {
	if x != nil {
		return x.TeamLeader
	}
	return ""
}

func (x *MatchWaiter) GetTeamMember() []string {
	if x != nil {
		return x.TeamMember
	}
	return nil
}

type Req_Node_NewMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Waiter *MatchWaiter `protobuf:"bytes,1,opt,name=waiter,proto3" json:"waiter,omitempty"`
}

func (x *Req_Node_NewMatch) Reset() {
	*x = Req_Node_NewMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_NewMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_NewMatch) ProtoMessage() {}

func (x *Req_Node_NewMatch) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_NewMatch.ProtoReflect.Descriptor instead.
func (*Req_Node_NewMatch) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{9}
}

func (x *Req_Node_NewMatch) GetWaiter() *MatchWaiter {
	if x != nil {
		return x.Waiter
	}
	return nil
}

type Rsp_Node_NewMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State            int32  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	ExpectedWaitTime int64  `protobuf:"varint,2,opt,name=expectedWaitTime,proto3" json:"expectedWaitTime,omitempty"`
	ErrReason        string `protobuf:"bytes,3,opt,name=errReason,proto3" json:"errReason,omitempty"`
}

func (x *Rsp_Node_NewMatch) Reset() {
	*x = Rsp_Node_NewMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_NewMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_NewMatch) ProtoMessage() {}

func (x *Rsp_Node_NewMatch) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_NewMatch.ProtoReflect.Descriptor instead.
func (*Rsp_Node_NewMatch) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{10}
}

func (x *Rsp_Node_NewMatch) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Rsp_Node_NewMatch) GetExpectedWaitTime() int64 {
	if x != nil {
		return x.ExpectedWaitTime
	}
	return 0
}

func (x *Rsp_Node_NewMatch) GetErrReason() string {
	if x != nil {
		return x.ErrReason
	}
	return ""
}

// 取消匹配
type Req_Node_CancelMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	ServerId int32 `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *Req_Node_CancelMatch) Reset() {
	*x = Req_Node_CancelMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_CancelMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_CancelMatch) ProtoMessage() {}

func (x *Req_Node_CancelMatch) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_CancelMatch.ProtoReflect.Descriptor instead.
func (*Req_Node_CancelMatch) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{11}
}

func (x *Req_Node_CancelMatch) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Req_Node_CancelMatch) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type Rsp_Node_CancelMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Rsp_Node_CancelMatch) Reset() {
	*x = Rsp_Node_CancelMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_CancelMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_CancelMatch) ProtoMessage() {}

func (x *Rsp_Node_CancelMatch) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_CancelMatch.ProtoReflect.Descriptor instead.
func (*Rsp_Node_CancelMatch) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{12}
}

func (x *Rsp_Node_CancelMatch) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// 匹配成功
type Req_Node_MatchSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State       int32    `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	MatchMember []string `protobuf:"bytes,2,rep,name=matchMember,proto3" json:"matchMember,omitempty"`
	RoomId      string   `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomAddr    string   `protobuf:"bytes,4,opt,name=roomAddr,proto3" json:"roomAddr,omitempty"`
}

func (x *Req_Node_MatchSuccess) Reset() {
	*x = Req_Node_MatchSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_MatchSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_MatchSuccess) ProtoMessage() {}

func (x *Req_Node_MatchSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_MatchSuccess.ProtoReflect.Descriptor instead.
func (*Req_Node_MatchSuccess) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{13}
}

func (x *Req_Node_MatchSuccess) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Req_Node_MatchSuccess) GetMatchMember() []string {
	if x != nil {
		return x.MatchMember
	}
	return nil
}

func (x *Req_Node_MatchSuccess) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Req_Node_MatchSuccess) GetRoomAddr() string {
	if x != nil {
		return x.RoomAddr
	}
	return ""
}

type Rsp_Node_MatchSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Rsp_Node_MatchSuccess) Reset() {
	*x = Rsp_Node_MatchSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_MatchSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_MatchSuccess) ProtoMessage() {}

func (x *Rsp_Node_MatchSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_MatchSuccess.ProtoReflect.Descriptor instead.
func (*Rsp_Node_MatchSuccess) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{14}
}

func (x *Rsp_Node_MatchSuccess) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// 创建房间
type Req_Node_CreateRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType    int32    `protobuf:"varint,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	ConfId      int32    `protobuf:"varint,2,opt,name=confId,proto3" json:"confId,omitempty"`
	MatchMember []string `protobuf:"bytes,3,rep,name=matchMember,proto3" json:"matchMember,omitempty"`
	MatchId     string   `protobuf:"bytes,4,opt,name=matchId,proto3" json:"matchId,omitempty"`
}

func (x *Req_Node_CreateRoom) Reset() {
	*x = Req_Node_CreateRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_CreateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_CreateRoom) ProtoMessage() {}

func (x *Req_Node_CreateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_CreateRoom.ProtoReflect.Descriptor instead.
func (*Req_Node_CreateRoom) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{15}
}

func (x *Req_Node_CreateRoom) GetRoomType() int32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *Req_Node_CreateRoom) GetConfId() int32 {
	if x != nil {
		return x.ConfId
	}
	return 0
}

func (x *Req_Node_CreateRoom) GetMatchMember() []string {
	if x != nil {
		return x.MatchMember
	}
	return nil
}

func (x *Req_Node_CreateRoom) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type Rsp_Node_CreateRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State    int32  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	RoomId   string `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomAddr string `protobuf:"bytes,3,opt,name=roomAddr,proto3" json:"roomAddr,omitempty"`
}

func (x *Rsp_Node_CreateRoom) Reset() {
	*x = Rsp_Node_CreateRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_CreateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_CreateRoom) ProtoMessage() {}

func (x *Rsp_Node_CreateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_CreateRoom.ProtoReflect.Descriptor instead.
func (*Rsp_Node_CreateRoom) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{16}
}

func (x *Rsp_Node_CreateRoom) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Rsp_Node_CreateRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Rsp_Node_CreateRoom) GetRoomAddr() string {
	if x != nil {
		return x.RoomAddr
	}
	return ""
}

type Req_Node_MakeConnToRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	RoomId   string `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomAddr string `protobuf:"bytes,3,opt,name=roomAddr,proto3" json:"roomAddr,omitempty"`
}

func (x *Req_Node_MakeConnToRoom) Reset() {
	*x = Req_Node_MakeConnToRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_MakeConnToRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_MakeConnToRoom) ProtoMessage() {}

func (x *Req_Node_MakeConnToRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_MakeConnToRoom.ProtoReflect.Descriptor instead.
func (*Req_Node_MakeConnToRoom) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{17}
}

func (x *Req_Node_MakeConnToRoom) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Req_Node_MakeConnToRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Req_Node_MakeConnToRoom) GetRoomAddr() string {
	if x != nil {
		return x.RoomAddr
	}
	return ""
}

type Rsp_Node_MakeConnToRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Rsp_Node_MakeConnToRoom) Reset() {
	*x = Rsp_Node_MakeConnToRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_MakeConnToRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_MakeConnToRoom) ProtoMessage() {}

func (x *Rsp_Node_MakeConnToRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_MakeConnToRoom.ProtoReflect.Descriptor instead.
func (*Rsp_Node_MakeConnToRoom) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{18}
}

func (x *Rsp_Node_MakeConnToRoom) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type Req_Node_EnterRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64        `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	RoomId   string       `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Actor    *BattleActor `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *Req_Node_EnterRoom) Reset() {
	*x = Req_Node_EnterRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_EnterRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_EnterRoom) ProtoMessage() {}

func (x *Req_Node_EnterRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_EnterRoom.ProtoReflect.Descriptor instead.
func (*Req_Node_EnterRoom) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{19}
}

func (x *Req_Node_EnterRoom) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Req_Node_EnterRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Req_Node_EnterRoom) GetActor() *BattleActor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type Rsp_Node_EnterRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Rsp_Node_EnterRoom) Reset() {
	*x = Rsp_Node_EnterRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_EnterRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_EnterRoom) ProtoMessage() {}

func (x *Rsp_Node_EnterRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_EnterRoom.ProtoReflect.Descriptor instead.
func (*Rsp_Node_EnterRoom) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{20}
}

func (x *Rsp_Node_EnterRoom) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type Req_Node_QuitRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	RoomId   string `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *Req_Node_QuitRoom) Reset() {
	*x = Req_Node_QuitRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_QuitRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_QuitRoom) ProtoMessage() {}

func (x *Req_Node_QuitRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_QuitRoom.ProtoReflect.Descriptor instead.
func (*Req_Node_QuitRoom) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{21}
}

func (x *Req_Node_QuitRoom) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Req_Node_QuitRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type Rsp_Node_QuitRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Rsp_Node_QuitRoom) Reset() {
	*x = Rsp_Node_QuitRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_QuitRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_QuitRoom) ProtoMessage() {}

func (x *Rsp_Node_QuitRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_QuitRoom.ProtoReflect.Descriptor instead.
func (*Rsp_Node_QuitRoom) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{22}
}

func (x *Rsp_Node_QuitRoom) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_msg_server_proto protoreflect.FileDescriptor

var file_msg_server_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x1a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x15, 0x52, 0x65,
	0x71, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x15, 0x52, 0x73, 0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65,
	0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x5f, 0x4e, 0x6f, 0x64,
	0x65, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x12, 0x52,
	0x73, 0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x66, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x5f, 0x4e,
	0x6f, 0x64, 0x65, 0x5f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x44, 0x0a, 0x12, 0x52, 0x73, 0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x50, 0x61, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x5f, 0x4e, 0x6f, 0x64,
	0x65, 0x5f, 0x4e, 0x65, 0x77, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d,
	0x61, 0x69, 0x6c, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x73, 0x70, 0x5f, 0x4e, 0x6f, 0x64,
	0x65, 0x5f, 0x4e, 0x65, 0x77, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x22, 0x7b, 0x0a,
	0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x57, 0x61, 0x69, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65,
	0x61, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65,
	0x61, 0x6d, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x65, 0x61, 0x6d, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65,
	0x61, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x11, 0x52, 0x65,
	0x71, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x29, 0x0a, 0x06, 0x77, 0x61, 0x69, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x57, 0x61, 0x69, 0x74,
	0x65, 0x72, 0x52, 0x06, 0x77, 0x61, 0x69, 0x74, 0x65, 0x72, 0x22, 0x73, 0x0a, 0x11, 0x52, 0x73,
	0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x57, 0x61, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x10, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x57, 0x61, 0x69, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x4e, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x2c, 0x0a, 0x14, 0x52, 0x73, 0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x83, 0x01,
	0x0a, 0x15, 0x52, 0x65, 0x71, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x41,
	0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x41,
	0x64, 0x64, 0x72, 0x22, 0x2d, 0x0a, 0x15, 0x52, 0x73, 0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x13, 0x52, 0x73,
	0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x22, 0x69, 0x0a, 0x17, 0x52,
	0x65, 0x71, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6e, 0x6e,
	0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x22, 0x2f, 0x0a, 0x17, 0x52, 0x73, 0x70, 0x5f, 0x4e, 0x6f,
	0x64, 0x65, 0x5f, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x54, 0x6f, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x71, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x5f, 0x4e,
	0x6f, 0x64, 0x65, 0x5f, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x2a, 0x0a, 0x12, 0x52, 0x73,
	0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x47, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x5f, 0x4e, 0x6f,
	0x64, 0x65, 0x5f, 0x51, 0x75, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22,
	0x29, 0x0a, 0x11, 0x52, 0x73, 0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x51, 0x75, 0x69, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_server_proto_rawDescOnce sync.Once
	file_msg_server_proto_rawDescData = file_msg_server_proto_rawDesc
)

func file_msg_server_proto_rawDescGZIP() []byte {
	file_msg_server_proto_rawDescOnce.Do(func() {
		file_msg_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_server_proto_rawDescData)
	})
	return file_msg_server_proto_rawDescData
}

var file_msg_server_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_msg_server_proto_goTypes = []interface{}{
	(*Req_Node_CreatePlayer)(nil),   // 0: game.Req_Node_CreatePlayer
	(*Rsp_Node_CreatePlayer)(nil),   // 1: game.Rsp_Node_CreatePlayer
	(*Req_Node_ConnCount)(nil),      // 2: game.Req_Node_ConnCount
	(*Rsp_Node_ConnCount)(nil),      // 3: game.Rsp_Node_ConnCount
	(*Req_Node_OrderPaid)(nil),      // 4: game.Req_Node_OrderPaid
	(*Rsp_Node_OrderPaid)(nil),      // 5: game.Rsp_Node_OrderPaid
	(*Req_Node_NewBaseMail)(nil),    // 6: game.Req_Node_NewBaseMail
	(*Rsp_Node_NewBaseMail)(nil),    // 7: game.Rsp_Node_NewBaseMail
	(*MatchWaiter)(nil),             // 8: game.MatchWaiter
	(*Req_Node_NewMatch)(nil),       // 9: game.Req_Node_NewMatch
	(*Rsp_Node_NewMatch)(nil),       // 10: game.Rsp_Node_NewMatch
	(*Req_Node_CancelMatch)(nil),    // 11: game.Req_Node_CancelMatch
	(*Rsp_Node_CancelMatch)(nil),    // 12: game.Rsp_Node_CancelMatch
	(*Req_Node_MatchSuccess)(nil),   // 13: game.Req_Node_MatchSuccess
	(*Rsp_Node_MatchSuccess)(nil),   // 14: game.Rsp_Node_MatchSuccess
	(*Req_Node_CreateRoom)(nil),     // 15: game.Req_Node_CreateRoom
	(*Rsp_Node_CreateRoom)(nil),     // 16: game.Rsp_Node_CreateRoom
	(*Req_Node_MakeConnToRoom)(nil), // 17: game.Req_Node_MakeConnToRoom
	(*Rsp_Node_MakeConnToRoom)(nil), // 18: game.Rsp_Node_MakeConnToRoom
	(*Req_Node_EnterRoom)(nil),      // 19: game.Req_Node_EnterRoom
	(*Rsp_Node_EnterRoom)(nil),      // 20: game.Rsp_Node_EnterRoom
	(*Req_Node_QuitRoom)(nil),       // 21: game.Req_Node_QuitRoom
	(*Rsp_Node_QuitRoom)(nil),       // 22: game.Rsp_Node_QuitRoom
	(*BattleActor)(nil),             // 23: game.BattleActor
}
var file_msg_server_proto_depIdxs = []int32{
	8,  // 0: game.Req_Node_NewMatch.waiter:type_name -> game.MatchWaiter
	23, // 1: game.Req_Node_EnterRoom.actor:type_name -> game.BattleActor
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_msg_server_proto_init() }
func file_msg_server_proto_init() {
	if File_msg_server_proto != nil {
		return
	}
	file_msg_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_CreatePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_CreatePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_ConnCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_ConnCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_OrderPaid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_OrderPaid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_NewBaseMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_NewBaseMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchWaiter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_NewMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_NewMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_CancelMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_CancelMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_MatchSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_MatchSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_CreateRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_CreateRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_MakeConnToRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_MakeConnToRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_EnterRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_EnterRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_QuitRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_QuitRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_server_proto_goTypes,
		DependencyIndexes: file_msg_server_proto_depIdxs,
		MessageInfos:      file_msg_server_proto_msgTypes,
	}.Build()
	File_msg_server_proto = out.File
	file_msg_server_proto_rawDesc = nil
	file_msg_server_proto_goTypes = nil
	file_msg_server_proto_depIdxs = nil
}
