// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: src/msg_http.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req_Http_CreatePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ServerID int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *Req_Http_CreatePlayer) Reset() {
	*x = Req_Http_CreatePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Http_CreatePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Http_CreatePlayer) ProtoMessage() {}

func (x *Req_Http_CreatePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Http_CreatePlayer.ProtoReflect.Descriptor instead.
func (*Req_Http_CreatePlayer) Descriptor() ([]byte, []int) {
	return file_src_msg_http_proto_rawDescGZIP(), []int{0}
}

func (x *Req_Http_CreatePlayer) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Req_Http_CreatePlayer) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Req_Http_CreatePlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type Rsp_Http_CreatePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID int64  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	ServerID int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	ID       int64  `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID   int64  `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	Nickname string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Token    string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Rsp_Http_CreatePlayer) Reset() {
	*x = Rsp_Http_CreatePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Http_CreatePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Http_CreatePlayer) ProtoMessage() {}

func (x *Rsp_Http_CreatePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Http_CreatePlayer.ProtoReflect.Descriptor instead.
func (*Rsp_Http_CreatePlayer) Descriptor() ([]byte, []int) {
	return file_src_msg_http_proto_rawDescGZIP(), []int{1}
}

func (x *Rsp_Http_CreatePlayer) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *Rsp_Http_CreatePlayer) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Rsp_Http_CreatePlayer) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Rsp_Http_CreatePlayer) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Rsp_Http_CreatePlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Rsp_Http_CreatePlayer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Req_Http_SelectPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID      int64 `protobuf:"varint,1,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID int32 `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	PlayerID int64 `protobuf:"varint,3,opt,name=playerID,proto3" json:"playerID,omitempty"`
}

func (x *Req_Http_SelectPlayer) Reset() {
	*x = Req_Http_SelectPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_http_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Http_SelectPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Http_SelectPlayer) ProtoMessage() {}

func (x *Req_Http_SelectPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_http_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Http_SelectPlayer.ProtoReflect.Descriptor instead.
func (*Req_Http_SelectPlayer) Descriptor() ([]byte, []int) {
	return file_src_msg_http_proto_rawDescGZIP(), []int{2}
}

func (x *Req_Http_SelectPlayer) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Req_Http_SelectPlayer) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Req_Http_SelectPlayer) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

type Rsp_Http_SelectPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID int64  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	ServerID int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	ID       int64  `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID   int64  `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	Nickname string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Token    string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Rsp_Http_SelectPlayer) Reset() {
	*x = Rsp_Http_SelectPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_http_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Http_SelectPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Http_SelectPlayer) ProtoMessage() {}

func (x *Rsp_Http_SelectPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_http_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Http_SelectPlayer.ProtoReflect.Descriptor instead.
func (*Rsp_Http_SelectPlayer) Descriptor() ([]byte, []int) {
	return file_src_msg_http_proto_rawDescGZIP(), []int{3}
}

func (x *Rsp_Http_SelectPlayer) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *Rsp_Http_SelectPlayer) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Rsp_Http_SelectPlayer) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Rsp_Http_SelectPlayer) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Rsp_Http_SelectPlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Rsp_Http_SelectPlayer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_src_msg_http_proto protoreflect.FileDescriptor

var file_src_msg_http_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x67, 0x0a, 0x15, 0x52, 0x65,
	0x71, 0x5f, 0x48, 0x74, 0x74, 0x70, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xa9, 0x01, 0x0a, 0x15, 0x52, 0x73, 0x70, 0x5f, 0x48, 0x74, 0x74, 0x70,
	0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x61, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x5f, 0x48, 0x74, 0x74, 0x70, 0x5f, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x44, 0x22, 0xa9, 0x01, 0x0a, 0x15, 0x52, 0x73, 0x70, 0x5f, 0x48, 0x74, 0x74, 0x70, 0x5f,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_msg_http_proto_rawDescOnce sync.Once
	file_src_msg_http_proto_rawDescData = file_src_msg_http_proto_rawDesc
)

func file_src_msg_http_proto_rawDescGZIP() []byte {
	file_src_msg_http_proto_rawDescOnce.Do(func() {
		file_src_msg_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_msg_http_proto_rawDescData)
	})
	return file_src_msg_http_proto_rawDescData
}

var file_src_msg_http_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_msg_http_proto_goTypes = []interface{}{
	(*Req_Http_CreatePlayer)(nil), // 0: game.Req_Http_CreatePlayer
	(*Rsp_Http_CreatePlayer)(nil), // 1: game.Rsp_Http_CreatePlayer
	(*Req_Http_SelectPlayer)(nil), // 2: game.Req_Http_SelectPlayer
	(*Rsp_Http_SelectPlayer)(nil), // 3: game.Rsp_Http_SelectPlayer
}
var file_src_msg_http_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_msg_http_proto_init() }
func file_src_msg_http_proto_init() {
	if File_src_msg_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_msg_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Http_CreatePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_http_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Http_CreatePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_http_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Http_SelectPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_http_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Http_SelectPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_msg_http_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_msg_http_proto_goTypes,
		DependencyIndexes: file_src_msg_http_proto_depIdxs,
		MessageInfos:      file_src_msg_http_proto_msgTypes,
	}.Build()
	File_src_msg_http_proto = out.File
	file_src_msg_http_proto_rawDesc = nil
	file_src_msg_http_proto_goTypes = nil
	file_src_msg_http_proto_depIdxs = nil
}
