// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: msg_battle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action_Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Action_Move) Reset() {
	*x = Action_Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Move) ProtoMessage() {}

func (x *Action_Move) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Move.ProtoReflect.Descriptor instead.
func (*Action_Move) Descriptor() ([]byte, []int) {
	return file_msg_battle_proto_rawDescGZIP(), []int{0}
}

func (x *Action_Move) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Action_Move) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Action_Move) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Action_UseSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillId   int32   `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	TargetIds []int64 `protobuf:"varint,2,rep,packed,name=targetIds,proto3" json:"targetIds,omitempty"`
}

func (x *Action_UseSkill) Reset() {
	*x = Action_UseSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_UseSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_UseSkill) ProtoMessage() {}

func (x *Action_UseSkill) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_UseSkill.ProtoReflect.Descriptor instead.
func (*Action_UseSkill) Descriptor() ([]byte, []int) {
	return file_msg_battle_proto_rawDescGZIP(), []int{1}
}

func (x *Action_UseSkill) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *Action_UseSkill) GetTargetIds() []int64 {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type ActorState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorId int64        `protobuf:"varint,1,opt,name=actorId,proto3" json:"actorId,omitempty"`
	Move    *Action_Move `protobuf:"bytes,2,opt,name=move,proto3" json:"move,omitempty"`
	IsMove  bool         `protobuf:"varint,3,opt,name=isMove,proto3" json:"isMove,omitempty"`
}

func (x *ActorState) Reset() {
	*x = ActorState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorState) ProtoMessage() {}

func (x *ActorState) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorState.ProtoReflect.Descriptor instead.
func (*ActorState) Descriptor() ([]byte, []int) {
	return file_msg_battle_proto_rawDescGZIP(), []int{2}
}

func (x *ActorState) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *ActorState) GetMove() *Action_Move {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *ActorState) GetIsMove() bool {
	if x != nil {
		return x.IsMove
	}
	return false
}

type SkillUseResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId int64   `protobuf:"varint,1,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Score    float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	IsCrit   bool    `protobuf:"varint,3,opt,name=isCrit,proto3" json:"isCrit,omitempty"`
	IsDodge  bool    `protobuf:"varint,4,opt,name=isDodge,proto3" json:"isDodge,omitempty"`
	IsBlock  bool    `protobuf:"varint,5,opt,name=isBlock,proto3" json:"isBlock,omitempty"`
}

func (x *SkillUseResult) Reset() {
	*x = SkillUseResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkillUseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillUseResult) ProtoMessage() {}

func (x *SkillUseResult) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillUseResult.ProtoReflect.Descriptor instead.
func (*SkillUseResult) Descriptor() ([]byte, []int) {
	return file_msg_battle_proto_rawDescGZIP(), []int{3}
}

func (x *SkillUseResult) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SkillUseResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SkillUseResult) GetIsCrit() bool {
	if x != nil {
		return x.IsCrit
	}
	return false
}

func (x *SkillUseResult) GetIsDodge() bool {
	if x != nil {
		return x.IsDodge
	}
	return false
}

func (x *SkillUseResult) GetIsBlock() bool {
	if x != nil {
		return x.IsBlock
	}
	return false
}

type GirdEvents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType   int32             `protobuf:"varint,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	SkillId     int32             `protobuf:"varint,2,opt,name=skillId,proto3" json:"skillId,omitempty"`
	CastActorId int64             `protobuf:"varint,3,opt,name=castActorId,proto3" json:"castActorId,omitempty"`
	Targets     []*SkillUseResult `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *GirdEvents) Reset() {
	*x = GirdEvents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GirdEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GirdEvents) ProtoMessage() {}

func (x *GirdEvents) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GirdEvents.ProtoReflect.Descriptor instead.
func (*GirdEvents) Descriptor() ([]byte, []int) {
	return file_msg_battle_proto_rawDescGZIP(), []int{4}
}

func (x *GirdEvents) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *GirdEvents) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *GirdEvents) GetCastActorId() int64 {
	if x != nil {
		return x.CastActorId
	}
	return 0
}

func (x *GirdEvents) GetTargets() []*SkillUseResult {
	if x != nil {
		return x.Targets
	}
	return nil
}

type WorldSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameId    int64         `protobuf:"varint,1,opt,name=frameId,proto3" json:"frameId,omitempty"`
	EnterList  []*ActorState `protobuf:"bytes,2,rep,name=enterList,proto3" json:"enterList,omitempty"`
	UpdateList []*ActorState `protobuf:"bytes,3,rep,name=updateList,proto3" json:"updateList,omitempty"`
	LeaveList  []int64       `protobuf:"varint,4,rep,packed,name=leaveList,proto3" json:"leaveList,omitempty"`
	Events     []*GirdEvents `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_msg_battle_proto_rawDescGZIP(), []int{5}
}

func (x *WorldSnapshot) GetFrameId() int64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *WorldSnapshot) GetEnterList() []*ActorState {
	if x != nil {
		return x.EnterList
	}
	return nil
}

func (x *WorldSnapshot) GetUpdateList() []*ActorState {
	if x != nil {
		return x.UpdateList
	}
	return nil
}

func (x *WorldSnapshot) GetLeaveList() []int64 {
	if x != nil {
		return x.LeaveList
	}
	return nil
}

func (x *WorldSnapshot) GetEvents() []*GirdEvents {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_msg_battle_proto protoreflect.FileDescriptor

var file_msg_battle_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01,
	0x7a, 0x22, 0x49, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x55, 0x73, 0x65, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x73, 0x22, 0x65, 0x0a, 0x0a,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x73, 0x4d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4d,
	0x6f, 0x76, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x55, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x43, 0x72,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x43, 0x72, 0x69, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x44, 0x6f, 0x64, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x44, 0x6f, 0x64, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x96, 0x01, 0x0a, 0x0a, 0x47, 0x69, 0x72, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x61, 0x73, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x63, 0x61, 0x73, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a,
	0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x22, 0xd3, 0x01,
	0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x09, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x65, 0x61, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09,
	0x6c, 0x65, 0x61, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x47, 0x69, 0x72, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x06, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_msg_battle_proto_rawDescOnce sync.Once
	file_msg_battle_proto_rawDescData = file_msg_battle_proto_rawDesc
)

func file_msg_battle_proto_rawDescGZIP() []byte {
	file_msg_battle_proto_rawDescOnce.Do(func() {
		file_msg_battle_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_battle_proto_rawDescData)
	})
	return file_msg_battle_proto_rawDescData
}

var file_msg_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_msg_battle_proto_goTypes = []interface{}{
	(*Action_Move)(nil),     // 0: game.Action_Move
	(*Action_UseSkill)(nil), // 1: game.Action_UseSkill
	(*ActorState)(nil),      // 2: game.ActorState
	(*SkillUseResult)(nil),  // 3: game.SkillUseResult
	(*GirdEvents)(nil),      // 4: game.GirdEvents
	(*WorldSnapshot)(nil),   // 5: game.WorldSnapshot
}
var file_msg_battle_proto_depIdxs = []int32{
	0, // 0: game.ActorState.move:type_name -> game.Action_Move
	3, // 1: game.GirdEvents.targets:type_name -> game.SkillUseResult
	2, // 2: game.WorldSnapshot.enterList:type_name -> game.ActorState
	2, // 3: game.WorldSnapshot.updateList:type_name -> game.ActorState
	4, // 4: game.WorldSnapshot.events:type_name -> game.GirdEvents
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_msg_battle_proto_init() }
func file_msg_battle_proto_init() {
	if File_msg_battle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_battle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_UseSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkillUseResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GirdEvents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorldSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_battle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_battle_proto_goTypes,
		DependencyIndexes: file_msg_battle_proto_depIdxs,
		MessageInfos:      file_msg_battle_proto_msgTypes,
	}.Build()
	File_msg_battle_proto = out.File
	file_msg_battle_proto_rawDesc = nil
	file_msg_battle_proto_goTypes = nil
	file_msg_battle_proto_depIdxs = nil
}
