// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: src/msg_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req_Node_CreatePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ServerID int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *Req_Node_CreatePlayer) Reset() {
	*x = Req_Node_CreatePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_CreatePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_CreatePlayer) ProtoMessage() {}

func (x *Req_Node_CreatePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_CreatePlayer.ProtoReflect.Descriptor instead.
func (*Req_Node_CreatePlayer) Descriptor() ([]byte, []int) {
	return file_src_msg_server_proto_rawDescGZIP(), []int{0}
}

func (x *Req_Node_CreatePlayer) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Req_Node_CreatePlayer) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Req_Node_CreatePlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type Rsp_Node_CreatePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID int64  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	ServerID int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	ID       int64  `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID   int64  `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	Nickname string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Token    string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	State    int32  `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Rsp_Node_CreatePlayer) Reset() {
	*x = Rsp_Node_CreatePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_CreatePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_CreatePlayer) ProtoMessage() {}

func (x *Rsp_Node_CreatePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_CreatePlayer.ProtoReflect.Descriptor instead.
func (*Rsp_Node_CreatePlayer) Descriptor() ([]byte, []int) {
	return file_src_msg_server_proto_rawDescGZIP(), []int{1}
}

func (x *Rsp_Node_CreatePlayer) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *Rsp_Node_CreatePlayer) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Rsp_Node_CreatePlayer) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Rsp_Node_CreatePlayer) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Rsp_Node_CreatePlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Rsp_Node_CreatePlayer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Rsp_Node_CreatePlayer) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type Req_Node_ConnCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Req_Node_ConnCount) Reset() {
	*x = Req_Node_ConnCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_ConnCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_ConnCount) ProtoMessage() {}

func (x *Req_Node_ConnCount) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_ConnCount.ProtoReflect.Descriptor instead.
func (*Req_Node_ConnCount) Descriptor() ([]byte, []int) {
	return file_src_msg_server_proto_rawDescGZIP(), []int{2}
}

type Rsp_Node_ConnCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *Rsp_Node_ConnCount) Reset() {
	*x = Rsp_Node_ConnCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_ConnCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_ConnCount) ProtoMessage() {}

func (x *Rsp_Node_ConnCount) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_ConnCount.ProtoReflect.Descriptor instead.
func (*Rsp_Node_ConnCount) Descriptor() ([]byte, []int) {
	return file_src_msg_server_proto_rawDescGZIP(), []int{3}
}

func (x *Rsp_Node_ConnCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Req_Node_OrderPaid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID int64  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	ServerID int32  `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	OrderId  string `protobuf:"bytes,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *Req_Node_OrderPaid) Reset() {
	*x = Req_Node_OrderPaid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Node_OrderPaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Node_OrderPaid) ProtoMessage() {}

func (x *Req_Node_OrderPaid) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Node_OrderPaid.ProtoReflect.Descriptor instead.
func (*Req_Node_OrderPaid) Descriptor() ([]byte, []int) {
	return file_src_msg_server_proto_rawDescGZIP(), []int{4}
}

func (x *Req_Node_OrderPaid) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *Req_Node_OrderPaid) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Req_Node_OrderPaid) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type Rsp_Node_OrderPaid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	State   int32  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Rsp_Node_OrderPaid) Reset() {
	*x = Rsp_Node_OrderPaid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_msg_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_Node_OrderPaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_Node_OrderPaid) ProtoMessage() {}

func (x *Rsp_Node_OrderPaid) ProtoReflect() protoreflect.Message {
	mi := &file_src_msg_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_Node_OrderPaid.ProtoReflect.Descriptor instead.
func (*Rsp_Node_OrderPaid) Descriptor() ([]byte, []int) {
	return file_src_msg_server_proto_rawDescGZIP(), []int{5}
}

func (x *Rsp_Node_OrderPaid) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Rsp_Node_OrderPaid) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_src_msg_server_proto protoreflect.FileDescriptor

var file_src_msg_server_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x67, 0x0a, 0x15,
	0x52, 0x65, 0x71, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x15, 0x52, 0x73, 0x70, 0x5f, 0x4e, 0x6f,
	0x64, 0x65, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x5f, 0x4e,
	0x6f, 0x64, 0x65, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2a, 0x0a,
	0x12, 0x52, 0x73, 0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x66, 0x0a, 0x12, 0x52, 0x65, 0x71,
	0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x44, 0x0a, 0x12, 0x52, 0x73, 0x70, 0x5f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_msg_server_proto_rawDescOnce sync.Once
	file_src_msg_server_proto_rawDescData = file_src_msg_server_proto_rawDesc
)

func file_src_msg_server_proto_rawDescGZIP() []byte {
	file_src_msg_server_proto_rawDescOnce.Do(func() {
		file_src_msg_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_msg_server_proto_rawDescData)
	})
	return file_src_msg_server_proto_rawDescData
}

var file_src_msg_server_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_src_msg_server_proto_goTypes = []interface{}{
	(*Req_Node_CreatePlayer)(nil), // 0: game.Req_Node_CreatePlayer
	(*Rsp_Node_CreatePlayer)(nil), // 1: game.Rsp_Node_CreatePlayer
	(*Req_Node_ConnCount)(nil),    // 2: game.Req_Node_ConnCount
	(*Rsp_Node_ConnCount)(nil),    // 3: game.Rsp_Node_ConnCount
	(*Req_Node_OrderPaid)(nil),    // 4: game.Req_Node_OrderPaid
	(*Rsp_Node_OrderPaid)(nil),    // 5: game.Rsp_Node_OrderPaid
}
var file_src_msg_server_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_msg_server_proto_init() }
func file_src_msg_server_proto_init() {
	if File_src_msg_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_msg_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_CreatePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_CreatePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_ConnCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_ConnCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Node_OrderPaid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_msg_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_Node_OrderPaid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_msg_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_msg_server_proto_goTypes,
		DependencyIndexes: file_src_msg_server_proto_depIdxs,
		MessageInfos:      file_src_msg_server_proto_msgTypes,
	}.Build()
	File_src_msg_server_proto = out.File
	file_src_msg_server_proto_rawDesc = nil
	file_src_msg_server_proto_goTypes = nil
	file_src_msg_server_proto_depIdxs = nil
}
