// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.8
// source: src/rpc_server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GameStreamService_Stream_FullMethodName = "/game.GameStreamService/Stream"
)

// GameStreamServiceClient is the client API for GameStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameStreamServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (GameStreamService_StreamClient, error)
}

type gameStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameStreamServiceClient(cc grpc.ClientConnInterface) GameStreamServiceClient {
	return &gameStreamServiceClient{cc}
}

func (c *gameStreamServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (GameStreamService_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GameStreamService_ServiceDesc.Streams[0], GameStreamService_Stream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gameStreamServiceStreamClient{stream}
	return x, nil
}

type GameStreamService_StreamClient interface {
	Send(*GameMessage) error
	Recv() (*GameMessage, error)
	grpc.ClientStream
}

type gameStreamServiceStreamClient struct {
	grpc.ClientStream
}

func (x *gameStreamServiceStreamClient) Send(m *GameMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameStreamServiceStreamClient) Recv() (*GameMessage, error) {
	m := new(GameMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameStreamServiceServer is the server API for GameStreamService service.
// All implementations must embed UnimplementedGameStreamServiceServer
// for forward compatibility
type GameStreamServiceServer interface {
	Stream(GameStreamService_StreamServer) error
	mustEmbedUnimplementedGameStreamServiceServer()
}

// UnimplementedGameStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameStreamServiceServer struct {
}

func (UnimplementedGameStreamServiceServer) Stream(GameStreamService_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGameStreamServiceServer) mustEmbedUnimplementedGameStreamServiceServer() {}

// UnsafeGameStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameStreamServiceServer will
// result in compilation errors.
type UnsafeGameStreamServiceServer interface {
	mustEmbedUnimplementedGameStreamServiceServer()
}

func RegisterGameStreamServiceServer(s grpc.ServiceRegistrar, srv GameStreamServiceServer) {
	s.RegisterService(&GameStreamService_ServiceDesc, srv)
}

func _GameStreamService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameStreamServiceServer).Stream(&gameStreamServiceStreamServer{stream})
}

type GameStreamService_StreamServer interface {
	Send(*GameMessage) error
	Recv() (*GameMessage, error)
	grpc.ServerStream
}

type gameStreamServiceStreamServer struct {
	grpc.ServerStream
}

func (x *gameStreamServiceStreamServer) Send(m *GameMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameStreamServiceStreamServer) Recv() (*GameMessage, error) {
	m := new(GameMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameStreamService_ServiceDesc is the grpc.ServiceDesc for GameStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameStreamService",
	HandlerType: (*GameStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _GameStreamService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/rpc_server.proto",
}

const (
	GameNodeService_LoginNodeCreatePlayer_FullMethodName = "/game.GameNodeService/LoginNodeCreatePlayer"
	GameNodeService_LoginNodeOrderPaid_FullMethodName    = "/game.GameNodeService/LoginNodeOrderPaid"
	GameNodeService_NotifyNewBaseMail_FullMethodName     = "/game.GameNodeService/NotifyNewBaseMail"
	GameNodeService_MatchNodeMatchSuccess_FullMethodName = "/game.GameNodeService/MatchNodeMatchSuccess"
)

// GameNodeServiceClient is the client API for GameNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameNodeServiceClient interface {
	// 登录服创建玩家
	LoginNodeCreatePlayer(ctx context.Context, in *Req_Node_CreatePlayer, opts ...grpc.CallOption) (*Rsp_Node_CreatePlayer, error)
	LoginNodeOrderPaid(ctx context.Context, in *Req_Node_OrderPaid, opts ...grpc.CallOption) (*Rsp_Node_OrderPaid, error)
	NotifyNewBaseMail(ctx context.Context, in *Req_Node_NewBaseMail, opts ...grpc.CallOption) (*Rsp_Node_NewBaseMail, error)
	MatchNodeMatchSuccess(ctx context.Context, in *Req_Node_MatchSuccess, opts ...grpc.CallOption) (*Rsp_Node_MatchSuccess, error)
}

type gameNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameNodeServiceClient(cc grpc.ClientConnInterface) GameNodeServiceClient {
	return &gameNodeServiceClient{cc}
}

func (c *gameNodeServiceClient) LoginNodeCreatePlayer(ctx context.Context, in *Req_Node_CreatePlayer, opts ...grpc.CallOption) (*Rsp_Node_CreatePlayer, error) {
	out := new(Rsp_Node_CreatePlayer)
	err := c.cc.Invoke(ctx, GameNodeService_LoginNodeCreatePlayer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameNodeServiceClient) LoginNodeOrderPaid(ctx context.Context, in *Req_Node_OrderPaid, opts ...grpc.CallOption) (*Rsp_Node_OrderPaid, error) {
	out := new(Rsp_Node_OrderPaid)
	err := c.cc.Invoke(ctx, GameNodeService_LoginNodeOrderPaid_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameNodeServiceClient) NotifyNewBaseMail(ctx context.Context, in *Req_Node_NewBaseMail, opts ...grpc.CallOption) (*Rsp_Node_NewBaseMail, error) {
	out := new(Rsp_Node_NewBaseMail)
	err := c.cc.Invoke(ctx, GameNodeService_NotifyNewBaseMail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameNodeServiceClient) MatchNodeMatchSuccess(ctx context.Context, in *Req_Node_MatchSuccess, opts ...grpc.CallOption) (*Rsp_Node_MatchSuccess, error) {
	out := new(Rsp_Node_MatchSuccess)
	err := c.cc.Invoke(ctx, GameNodeService_MatchNodeMatchSuccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameNodeServiceServer is the server API for GameNodeService service.
// All implementations must embed UnimplementedGameNodeServiceServer
// for forward compatibility
type GameNodeServiceServer interface {
	// 登录服创建玩家
	LoginNodeCreatePlayer(context.Context, *Req_Node_CreatePlayer) (*Rsp_Node_CreatePlayer, error)
	LoginNodeOrderPaid(context.Context, *Req_Node_OrderPaid) (*Rsp_Node_OrderPaid, error)
	NotifyNewBaseMail(context.Context, *Req_Node_NewBaseMail) (*Rsp_Node_NewBaseMail, error)
	MatchNodeMatchSuccess(context.Context, *Req_Node_MatchSuccess) (*Rsp_Node_MatchSuccess, error)
	mustEmbedUnimplementedGameNodeServiceServer()
}

// UnimplementedGameNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameNodeServiceServer struct {
}

func (UnimplementedGameNodeServiceServer) LoginNodeCreatePlayer(context.Context, *Req_Node_CreatePlayer) (*Rsp_Node_CreatePlayer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginNodeCreatePlayer not implemented")
}
func (UnimplementedGameNodeServiceServer) LoginNodeOrderPaid(context.Context, *Req_Node_OrderPaid) (*Rsp_Node_OrderPaid, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginNodeOrderPaid not implemented")
}
func (UnimplementedGameNodeServiceServer) NotifyNewBaseMail(context.Context, *Req_Node_NewBaseMail) (*Rsp_Node_NewBaseMail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyNewBaseMail not implemented")
}
func (UnimplementedGameNodeServiceServer) MatchNodeMatchSuccess(context.Context, *Req_Node_MatchSuccess) (*Rsp_Node_MatchSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MatchNodeMatchSuccess not implemented")
}
func (UnimplementedGameNodeServiceServer) mustEmbedUnimplementedGameNodeServiceServer() {}

// UnsafeGameNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameNodeServiceServer will
// result in compilation errors.
type UnsafeGameNodeServiceServer interface {
	mustEmbedUnimplementedGameNodeServiceServer()
}

func RegisterGameNodeServiceServer(s grpc.ServiceRegistrar, srv GameNodeServiceServer) {
	s.RegisterService(&GameNodeService_ServiceDesc, srv)
}

func _GameNodeService_LoginNodeCreatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_CreatePlayer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameNodeServiceServer).LoginNodeCreatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameNodeService_LoginNodeCreatePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameNodeServiceServer).LoginNodeCreatePlayer(ctx, req.(*Req_Node_CreatePlayer))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameNodeService_LoginNodeOrderPaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_OrderPaid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameNodeServiceServer).LoginNodeOrderPaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameNodeService_LoginNodeOrderPaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameNodeServiceServer).LoginNodeOrderPaid(ctx, req.(*Req_Node_OrderPaid))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameNodeService_NotifyNewBaseMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_NewBaseMail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameNodeServiceServer).NotifyNewBaseMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameNodeService_NotifyNewBaseMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameNodeServiceServer).NotifyNewBaseMail(ctx, req.(*Req_Node_NewBaseMail))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameNodeService_MatchNodeMatchSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_MatchSuccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameNodeServiceServer).MatchNodeMatchSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameNodeService_MatchNodeMatchSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameNodeServiceServer).MatchNodeMatchSuccess(ctx, req.(*Req_Node_MatchSuccess))
	}
	return interceptor(ctx, in, info, handler)
}

// GameNodeService_ServiceDesc is the grpc.ServiceDesc for GameNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameNodeService",
	HandlerType: (*GameNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginNodeCreatePlayer",
			Handler:    _GameNodeService_LoginNodeCreatePlayer_Handler,
		},
		{
			MethodName: "LoginNodeOrderPaid",
			Handler:    _GameNodeService_LoginNodeOrderPaid_Handler,
		},
		{
			MethodName: "NotifyNewBaseMail",
			Handler:    _GameNodeService_NotifyNewBaseMail_Handler,
		},
		{
			MethodName: "MatchNodeMatchSuccess",
			Handler:    _GameNodeService_MatchNodeMatchSuccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/rpc_server.proto",
}

const (
	GatewayNodeService_GetConnCount_FullMethodName = "/game.GatewayNodeService/GetConnCount"
	GatewayNodeService_ConnToRoom_FullMethodName   = "/game.GatewayNodeService/ConnToRoom"
)

// GatewayNodeServiceClient is the client API for GatewayNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayNodeServiceClient interface {
	// 登录服创建玩家
	GetConnCount(ctx context.Context, in *Req_Node_ConnCount, opts ...grpc.CallOption) (*Rsp_Node_ConnCount, error)
	ConnToRoom(ctx context.Context, in *Req_Node_MakeConnToRoom, opts ...grpc.CallOption) (*Rsp_Node_MakeConnToRoom, error)
}

type gatewayNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayNodeServiceClient(cc grpc.ClientConnInterface) GatewayNodeServiceClient {
	return &gatewayNodeServiceClient{cc}
}

func (c *gatewayNodeServiceClient) GetConnCount(ctx context.Context, in *Req_Node_ConnCount, opts ...grpc.CallOption) (*Rsp_Node_ConnCount, error) {
	out := new(Rsp_Node_ConnCount)
	err := c.cc.Invoke(ctx, GatewayNodeService_GetConnCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNodeServiceClient) ConnToRoom(ctx context.Context, in *Req_Node_MakeConnToRoom, opts ...grpc.CallOption) (*Rsp_Node_MakeConnToRoom, error) {
	out := new(Rsp_Node_MakeConnToRoom)
	err := c.cc.Invoke(ctx, GatewayNodeService_ConnToRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayNodeServiceServer is the server API for GatewayNodeService service.
// All implementations must embed UnimplementedGatewayNodeServiceServer
// for forward compatibility
type GatewayNodeServiceServer interface {
	// 登录服创建玩家
	GetConnCount(context.Context, *Req_Node_ConnCount) (*Rsp_Node_ConnCount, error)
	ConnToRoom(context.Context, *Req_Node_MakeConnToRoom) (*Rsp_Node_MakeConnToRoom, error)
	mustEmbedUnimplementedGatewayNodeServiceServer()
}

// UnimplementedGatewayNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayNodeServiceServer struct {
}

func (UnimplementedGatewayNodeServiceServer) GetConnCount(context.Context, *Req_Node_ConnCount) (*Rsp_Node_ConnCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnCount not implemented")
}
func (UnimplementedGatewayNodeServiceServer) ConnToRoom(context.Context, *Req_Node_MakeConnToRoom) (*Rsp_Node_MakeConnToRoom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnToRoom not implemented")
}
func (UnimplementedGatewayNodeServiceServer) mustEmbedUnimplementedGatewayNodeServiceServer() {}

// UnsafeGatewayNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayNodeServiceServer will
// result in compilation errors.
type UnsafeGatewayNodeServiceServer interface {
	mustEmbedUnimplementedGatewayNodeServiceServer()
}

func RegisterGatewayNodeServiceServer(s grpc.ServiceRegistrar, srv GatewayNodeServiceServer) {
	s.RegisterService(&GatewayNodeService_ServiceDesc, srv)
}

func _GatewayNodeService_GetConnCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_ConnCount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNodeServiceServer).GetConnCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNodeService_GetConnCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNodeServiceServer).GetConnCount(ctx, req.(*Req_Node_ConnCount))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNodeService_ConnToRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_MakeConnToRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNodeServiceServer).ConnToRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNodeService_ConnToRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNodeServiceServer).ConnToRoom(ctx, req.(*Req_Node_MakeConnToRoom))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayNodeService_ServiceDesc is the grpc.ServiceDesc for GatewayNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GatewayNodeService",
	HandlerType: (*GatewayNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConnCount",
			Handler:    _GatewayNodeService_GetConnCount_Handler,
		},
		{
			MethodName: "ConnToRoom",
			Handler:    _GatewayNodeService_ConnToRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/rpc_server.proto",
}

const (
	MatchNodeService_StartMatch_FullMethodName  = "/game.MatchNodeService/StartMatch"
	MatchNodeService_CancelMatch_FullMethodName = "/game.MatchNodeService/CancelMatch"
)

// MatchNodeServiceClient is the client API for MatchNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchNodeServiceClient interface {
	StartMatch(ctx context.Context, in *Req_Node_NewMatch, opts ...grpc.CallOption) (*Rsp_Node_NewMatch, error)
	CancelMatch(ctx context.Context, in *Req_Node_CancelMatch, opts ...grpc.CallOption) (*Rsp_Node_CancelMatch, error)
}

type matchNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchNodeServiceClient(cc grpc.ClientConnInterface) MatchNodeServiceClient {
	return &matchNodeServiceClient{cc}
}

func (c *matchNodeServiceClient) StartMatch(ctx context.Context, in *Req_Node_NewMatch, opts ...grpc.CallOption) (*Rsp_Node_NewMatch, error) {
	out := new(Rsp_Node_NewMatch)
	err := c.cc.Invoke(ctx, MatchNodeService_StartMatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchNodeServiceClient) CancelMatch(ctx context.Context, in *Req_Node_CancelMatch, opts ...grpc.CallOption) (*Rsp_Node_CancelMatch, error) {
	out := new(Rsp_Node_CancelMatch)
	err := c.cc.Invoke(ctx, MatchNodeService_CancelMatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchNodeServiceServer is the server API for MatchNodeService service.
// All implementations must embed UnimplementedMatchNodeServiceServer
// for forward compatibility
type MatchNodeServiceServer interface {
	StartMatch(context.Context, *Req_Node_NewMatch) (*Rsp_Node_NewMatch, error)
	CancelMatch(context.Context, *Req_Node_CancelMatch) (*Rsp_Node_CancelMatch, error)
	mustEmbedUnimplementedMatchNodeServiceServer()
}

// UnimplementedMatchNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMatchNodeServiceServer struct {
}

func (UnimplementedMatchNodeServiceServer) StartMatch(context.Context, *Req_Node_NewMatch) (*Rsp_Node_NewMatch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMatch not implemented")
}
func (UnimplementedMatchNodeServiceServer) CancelMatch(context.Context, *Req_Node_CancelMatch) (*Rsp_Node_CancelMatch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMatch not implemented")
}
func (UnimplementedMatchNodeServiceServer) mustEmbedUnimplementedMatchNodeServiceServer() {}

// UnsafeMatchNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchNodeServiceServer will
// result in compilation errors.
type UnsafeMatchNodeServiceServer interface {
	mustEmbedUnimplementedMatchNodeServiceServer()
}

func RegisterMatchNodeServiceServer(s grpc.ServiceRegistrar, srv MatchNodeServiceServer) {
	s.RegisterService(&MatchNodeService_ServiceDesc, srv)
}

func _MatchNodeService_StartMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_NewMatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchNodeServiceServer).StartMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchNodeService_StartMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchNodeServiceServer).StartMatch(ctx, req.(*Req_Node_NewMatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchNodeService_CancelMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_CancelMatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchNodeServiceServer).CancelMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchNodeService_CancelMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchNodeServiceServer).CancelMatch(ctx, req.(*Req_Node_CancelMatch))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchNodeService_ServiceDesc is the grpc.ServiceDesc for MatchNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.MatchNodeService",
	HandlerType: (*MatchNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartMatch",
			Handler:    _MatchNodeService_StartMatch_Handler,
		},
		{
			MethodName: "CancelMatch",
			Handler:    _MatchNodeService_CancelMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/rpc_server.proto",
}

const (
	RoomManagerNodeService_AuthorityCreateRoom_FullMethodName = "/game.RoomManagerNodeService/AuthorityCreateRoom"
)

// RoomManagerNodeServiceClient is the client API for RoomManagerNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomManagerNodeServiceClient interface {
	AuthorityCreateRoom(ctx context.Context, in *Req_Node_CreateRoom, opts ...grpc.CallOption) (*Rsp_Node_CreateRoom, error)
}

type roomManagerNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomManagerNodeServiceClient(cc grpc.ClientConnInterface) RoomManagerNodeServiceClient {
	return &roomManagerNodeServiceClient{cc}
}

func (c *roomManagerNodeServiceClient) AuthorityCreateRoom(ctx context.Context, in *Req_Node_CreateRoom, opts ...grpc.CallOption) (*Rsp_Node_CreateRoom, error) {
	out := new(Rsp_Node_CreateRoom)
	err := c.cc.Invoke(ctx, RoomManagerNodeService_AuthorityCreateRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomManagerNodeServiceServer is the server API for RoomManagerNodeService service.
// All implementations must embed UnimplementedRoomManagerNodeServiceServer
// for forward compatibility
type RoomManagerNodeServiceServer interface {
	AuthorityCreateRoom(context.Context, *Req_Node_CreateRoom) (*Rsp_Node_CreateRoom, error)
	mustEmbedUnimplementedRoomManagerNodeServiceServer()
}

// UnimplementedRoomManagerNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRoomManagerNodeServiceServer struct {
}

func (UnimplementedRoomManagerNodeServiceServer) AuthorityCreateRoom(context.Context, *Req_Node_CreateRoom) (*Rsp_Node_CreateRoom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorityCreateRoom not implemented")
}
func (UnimplementedRoomManagerNodeServiceServer) mustEmbedUnimplementedRoomManagerNodeServiceServer() {
}

// UnsafeRoomManagerNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomManagerNodeServiceServer will
// result in compilation errors.
type UnsafeRoomManagerNodeServiceServer interface {
	mustEmbedUnimplementedRoomManagerNodeServiceServer()
}

func RegisterRoomManagerNodeServiceServer(s grpc.ServiceRegistrar, srv RoomManagerNodeServiceServer) {
	s.RegisterService(&RoomManagerNodeService_ServiceDesc, srv)
}

func _RoomManagerNodeService_AuthorityCreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_CreateRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagerNodeServiceServer).AuthorityCreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomManagerNodeService_AuthorityCreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagerNodeServiceServer).AuthorityCreateRoom(ctx, req.(*Req_Node_CreateRoom))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomManagerNodeService_ServiceDesc is the grpc.ServiceDesc for RoomManagerNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomManagerNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.RoomManagerNodeService",
	HandlerType: (*RoomManagerNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorityCreateRoom",
			Handler:    _RoomManagerNodeService_AuthorityCreateRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/rpc_server.proto",
}

const (
	RoomNodeService_CreateRoom_FullMethodName = "/game.RoomNodeService/CreateRoom"
	RoomNodeService_EnterRoom_FullMethodName  = "/game.RoomNodeService/EnterRoom"
	RoomNodeService_QuitRoom_FullMethodName   = "/game.RoomNodeService/QuitRoom"
)

// RoomNodeServiceClient is the client API for RoomNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomNodeServiceClient interface {
	CreateRoom(ctx context.Context, in *Req_Node_CreateRoom, opts ...grpc.CallOption) (*Rsp_Node_CreateRoom, error)
	EnterRoom(ctx context.Context, in *Req_Node_EnterRoom, opts ...grpc.CallOption) (*Rsp_Node_EnterRoom, error)
	QuitRoom(ctx context.Context, in *Req_Node_QuitRoom, opts ...grpc.CallOption) (*Rsp_Node_QuitRoom, error)
}

type roomNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomNodeServiceClient(cc grpc.ClientConnInterface) RoomNodeServiceClient {
	return &roomNodeServiceClient{cc}
}

func (c *roomNodeServiceClient) CreateRoom(ctx context.Context, in *Req_Node_CreateRoom, opts ...grpc.CallOption) (*Rsp_Node_CreateRoom, error) {
	out := new(Rsp_Node_CreateRoom)
	err := c.cc.Invoke(ctx, RoomNodeService_CreateRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomNodeServiceClient) EnterRoom(ctx context.Context, in *Req_Node_EnterRoom, opts ...grpc.CallOption) (*Rsp_Node_EnterRoom, error) {
	out := new(Rsp_Node_EnterRoom)
	err := c.cc.Invoke(ctx, RoomNodeService_EnterRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomNodeServiceClient) QuitRoom(ctx context.Context, in *Req_Node_QuitRoom, opts ...grpc.CallOption) (*Rsp_Node_QuitRoom, error) {
	out := new(Rsp_Node_QuitRoom)
	err := c.cc.Invoke(ctx, RoomNodeService_QuitRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomNodeServiceServer is the server API for RoomNodeService service.
// All implementations must embed UnimplementedRoomNodeServiceServer
// for forward compatibility
type RoomNodeServiceServer interface {
	CreateRoom(context.Context, *Req_Node_CreateRoom) (*Rsp_Node_CreateRoom, error)
	EnterRoom(context.Context, *Req_Node_EnterRoom) (*Rsp_Node_EnterRoom, error)
	QuitRoom(context.Context, *Req_Node_QuitRoom) (*Rsp_Node_QuitRoom, error)
	mustEmbedUnimplementedRoomNodeServiceServer()
}

// UnimplementedRoomNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRoomNodeServiceServer struct {
}

func (UnimplementedRoomNodeServiceServer) CreateRoom(context.Context, *Req_Node_CreateRoom) (*Rsp_Node_CreateRoom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedRoomNodeServiceServer) EnterRoom(context.Context, *Req_Node_EnterRoom) (*Rsp_Node_EnterRoom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnterRoom not implemented")
}
func (UnimplementedRoomNodeServiceServer) QuitRoom(context.Context, *Req_Node_QuitRoom) (*Rsp_Node_QuitRoom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitRoom not implemented")
}
func (UnimplementedRoomNodeServiceServer) mustEmbedUnimplementedRoomNodeServiceServer() {}

// UnsafeRoomNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomNodeServiceServer will
// result in compilation errors.
type UnsafeRoomNodeServiceServer interface {
	mustEmbedUnimplementedRoomNodeServiceServer()
}

func RegisterRoomNodeServiceServer(s grpc.ServiceRegistrar, srv RoomNodeServiceServer) {
	s.RegisterService(&RoomNodeService_ServiceDesc, srv)
}

func _RoomNodeService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_CreateRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomNodeServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomNodeService_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomNodeServiceServer).CreateRoom(ctx, req.(*Req_Node_CreateRoom))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomNodeService_EnterRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_EnterRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomNodeServiceServer).EnterRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomNodeService_EnterRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomNodeServiceServer).EnterRoom(ctx, req.(*Req_Node_EnterRoom))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomNodeService_QuitRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req_Node_QuitRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomNodeServiceServer).QuitRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomNodeService_QuitRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomNodeServiceServer).QuitRoom(ctx, req.(*Req_Node_QuitRoom))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomNodeService_ServiceDesc is the grpc.ServiceDesc for RoomNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.RoomNodeService",
	HandlerType: (*RoomNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomNodeService_CreateRoom_Handler,
		},
		{
			MethodName: "EnterRoom",
			Handler:    _RoomNodeService_EnterRoom_Handler,
		},
		{
			MethodName: "QuitRoom",
			Handler:    _RoomNodeService_QuitRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/rpc_server.proto",
}

const (
	RoomStreamService_Stream_FullMethodName = "/game.RoomStreamService/Stream"
)

// RoomStreamServiceClient is the client API for RoomStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomStreamServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (RoomStreamService_StreamClient, error)
}

type roomStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomStreamServiceClient(cc grpc.ClientConnInterface) RoomStreamServiceClient {
	return &roomStreamServiceClient{cc}
}

func (c *roomStreamServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (RoomStreamService_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &RoomStreamService_ServiceDesc.Streams[0], RoomStreamService_Stream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &roomStreamServiceStreamClient{stream}
	return x, nil
}

type RoomStreamService_StreamClient interface {
	Send(*GameMessage) error
	Recv() (*GameMessage, error)
	grpc.ClientStream
}

type roomStreamServiceStreamClient struct {
	grpc.ClientStream
}

func (x *roomStreamServiceStreamClient) Send(m *GameMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *roomStreamServiceStreamClient) Recv() (*GameMessage, error) {
	m := new(GameMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RoomStreamServiceServer is the server API for RoomStreamService service.
// All implementations must embed UnimplementedRoomStreamServiceServer
// for forward compatibility
type RoomStreamServiceServer interface {
	Stream(RoomStreamService_StreamServer) error
	mustEmbedUnimplementedRoomStreamServiceServer()
}

// UnimplementedRoomStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRoomStreamServiceServer struct {
}

func (UnimplementedRoomStreamServiceServer) Stream(RoomStreamService_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedRoomStreamServiceServer) mustEmbedUnimplementedRoomStreamServiceServer() {}

// UnsafeRoomStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomStreamServiceServer will
// result in compilation errors.
type UnsafeRoomStreamServiceServer interface {
	mustEmbedUnimplementedRoomStreamServiceServer()
}

func RegisterRoomStreamServiceServer(s grpc.ServiceRegistrar, srv RoomStreamServiceServer) {
	s.RegisterService(&RoomStreamService_ServiceDesc, srv)
}

func _RoomStreamService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RoomStreamServiceServer).Stream(&roomStreamServiceStreamServer{stream})
}

type RoomStreamService_StreamServer interface {
	Send(*GameMessage) error
	Recv() (*GameMessage, error)
	grpc.ServerStream
}

type roomStreamServiceStreamServer struct {
	grpc.ServerStream
}

func (x *roomStreamServiceStreamServer) Send(m *GameMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *roomStreamServiceStreamServer) Recv() (*GameMessage, error) {
	m := new(GameMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RoomStreamService_ServiceDesc is the grpc.ServiceDesc for RoomStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.RoomStreamService",
	HandlerType: (*RoomStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _RoomStreamService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/rpc_server.proto",
}
