// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: src/rpc_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端 → 游戏服（只需要协议号 + 二进制数据）
type ClientPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId MsgID  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3,enum=game.MsgID" json:"msg_id,omitempty"` // 协议ID
	Body  []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`                                 // proto 数据
}

func (x *ClientPacket) Reset() {
	*x = ClientPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_rpc_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPacket) ProtoMessage() {}

func (x *ClientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPacket.ProtoReflect.Descriptor instead.
func (*ClientPacket) Descriptor() ([]byte, []int) {
	return file_src_rpc_server_proto_rawDescGZIP(), []int{0}
}

func (x *ClientPacket) GetMsgId() MsgID {
	if x != nil {
		return x.MsgId
	}
	return MsgID_MSG_INVALID
}

func (x *ClientPacket) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 游戏服 → 客户端（只需要协议号 + 二进制数据）
type ServerPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId MsgID  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3,enum=game.MsgID" json:"msg_id,omitempty"`
	Body  []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ServerPacket) Reset() {
	*x = ServerPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_rpc_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket) ProtoMessage() {}

func (x *ServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket.ProtoReflect.Descriptor instead.
func (*ServerPacket) Descriptor() ([]byte, []int) {
	return file_src_rpc_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerPacket) GetMsgId() MsgID {
	if x != nil {
		return x.MsgId
	}
	return MsgID_MSG_INVALID
}

func (x *ServerPacket) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_src_rpc_server_proto protoreflect.FileDescriptor

var file_src_rpc_server_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x1a, 0x12, 0x73, 0x72,
	0x63, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x46, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x22, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x52, 0x05, 0x6d,
	0x73, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x46, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x4d, 0x73, 0x67, 0x49, 0x44, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x32, 0x45, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x36, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x12, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_rpc_server_proto_rawDescOnce sync.Once
	file_src_rpc_server_proto_rawDescData = file_src_rpc_server_proto_rawDesc
)

func file_src_rpc_server_proto_rawDescGZIP() []byte {
	file_src_rpc_server_proto_rawDescOnce.Do(func() {
		file_src_rpc_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_rpc_server_proto_rawDescData)
	})
	return file_src_rpc_server_proto_rawDescData
}

var file_src_rpc_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_rpc_server_proto_goTypes = []interface{}{
	(*ClientPacket)(nil), // 0: game.ClientPacket
	(*ServerPacket)(nil), // 1: game.ServerPacket
	(MsgID)(0),           // 2: game.MsgID
}
var file_src_rpc_server_proto_depIdxs = []int32{
	2, // 0: game.ClientPacket.msg_id:type_name -> game.MsgID
	2, // 1: game.ServerPacket.msg_id:type_name -> game.MsgID
	0, // 2: game.GameService.Stream:input_type -> game.ClientPacket
	1, // 3: game.GameService.Stream:output_type -> game.ServerPacket
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_rpc_server_proto_init() }
func file_src_rpc_server_proto_init() {
	if File_src_rpc_server_proto != nil {
		return
	}
	file_src_msg_code_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_src_rpc_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_rpc_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_rpc_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_rpc_server_proto_goTypes,
		DependencyIndexes: file_src_rpc_server_proto_depIdxs,
		MessageInfos:      file_src_rpc_server_proto_msgTypes,
	}.Build()
	File_src_rpc_server_proto = out.File
	file_src_rpc_server_proto_rawDesc = nil
	file_src_rpc_server_proto_goTypes = nil
	file_src_rpc_server_proto_depIdxs = nil
}
